[tool.poetry]
name = "python-sqlalquemy"
version = "0.1.0"
description = "projeto de python"
authors = ["william"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.31"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
